package com.openscholar.access.internal.verification;

public enum LinkVerificationFailure {
	NONE,
	SOURCE_NOT_PROVIDER,
	INVALID_URL,
	HTTPS_REQUIRED,
	CREDENTIALS_NOT_ALLOWED,
	FRAGMENT_NOT_ALLOWED,
	NON_DEFAULT_PORT_NOT_ALLOWED,
	DNS_RESOLUTION_FAILED,
	ADDRESS_NOT_PUBLIC,
	NETWORK_ERROR,
	REQUEST_INTERRUPTED,
	HTTP_STATUS_REJECTED,
	REDIRECT_LOCATION_MISSING,
	INVALID_REDIRECT,
	TOO_MANY_REDIRECTS,
	PDF_CONTENT_NOT_VERIFIED
}
